### ISSUE TITLE
Write script to "report" on tables

### ISSUE THREAD

**Issue by beckyjackson** [IEDB/ONTIE#23]
This script should run some ROBOT report checks like annotation whitespace, duplicate labels, duplicate definitions, etc. over all the templates and return a standardized problems table like the one described in https://github.com/ontodev/robot/issues/712

Try python first, but if it's very slow, we will use SQLite for this.

This will go in one big branch for all the work hooking ONTIE up to DROID.

**Comment by beckyjackson** [comment]
Things we can check:
* annotation whitespace
* duplicate synonyms
* duplicate labels
* label formatting (using new lines or tabs in labels)
* label whitespace
* lowercase definition
* missing definitions
* missing label
* missing obsolete label
* missing superclass (maybe?)
* multiple definitions
* multiple labels

**Comment by jamesaoverton** [comment]
This is a good list. Two notes:

1. I'd be happy to start with just a few of these, to demonstrate how it works, and add the rest later.
2. Some of these might return false negatives, since they won't have all the information they need for a thorough check, but that's fine. For example, if a term in the template has definition X, and an imported term also has definition X, this validation won't catch that duplicate. But running `robot report` on the full OWL file will catch it, so I'm not worried about such cases.

**Comment by beckyjackson** [comment]
I was able to implement all of these pretty easily, but it's a bit of a mess as far as the script goes... I'm not sure the best way to write something that would applicable across different templates, because this is assuming that each template is structured in the way we structure them for ONTIE.

Another question:
How do we want to handle sheets that do not have a "Definition" column (e.g. proteins)? A missing definition is a warning, but there's no cell to highlight in this case because the column doesn't exist.

**Comment by jamesaoverton** [comment]
We'll want to generalize this, but not yet.

For the sheets without a definition column, I'd prefer to ignore the missing definition problem for now. It will show up in `robot report`. We'll have to fix that eventually, but right now I'm more interested in getting the new systems working end-to-end.
