### ISSUE TITLE
Failed to connect to build.obolibrary.io port 443

### ISSUE THREAD

**Issue by opqi** [IEDB/ONTIE#72]
curl -L -o build/robot-report.jar https://build.obolibrary.io/job/ontodev/job/robot/job/html-report/lastSuccessfulBuild/artifact/bin/robot.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:31 --:--:--     0curl: (7) Failed to connect to build.obolibrary.io port 443: Connection timed out
Makefile:46: recipe for target 'build/robot-report.jar' failed
make: *** [build/robot-report.jar] Error 7

**Comment by jamesaoverton** [comment]
Thanks for the report. I'll fix that properly when I get back from vacation.

In the meantime I expect that the `build/robot.jar` (version 1.8.1) can be used instead of `build/robot-report.jar`. If that doesn't work, the the latest `robot.jar` from the official releases page (1.9.0) should work: <https://github.com/ontodev/robot/releases>.
